FROM postgres:latest
ENV POSTGRES_PASSWORD=secret
ENV POSTGRES_USER=username
ENV POSTGRES_DB=database
ENV POSTGRES_HOST=localhost
COPY initial_tables.sql /docker-entrypoint-initdb.d/initial_tables.sql
#CMD [ "tail -f /dev/null" ]